# Generated by Django 5.1.5 on 2026-01-28 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_id', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('academic_status', models.CharField(max_length=20)),
                ('part', models.CharField(choices=[('FE', '프론트엔드'), ('BE', '백엔드'), ('PD', '기획/디자인')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('answer', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_answers', to='application.application')),
            ],
            options={
                'unique_together': {('application', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='PartSpecificAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('answer', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_answers', to='application.application')),
            ],
            options={
                'unique_together': {('application', 'question_number')},
            },
        ),
    ]
